name: Workflow Sekolahlinux

on: workflow_dispatch

jobs:
  update-readme:
#    runs-on: ubuntu-latest
    runs-on: sekolahlinux-runner
    container: bitnami/git:2-debian-11
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: load secret from vault
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: http://10.13.3.243:8200
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            development/data/service-a content;
      - name: update Index
        run: |
          apt update && apt install gettext-base -y
          envsubst < README.md-template > README.md
          git config --global user.email "admin@sekolahlinux.com"
          git config --global user.name "admin"
          git add -A && git commit -m "update"          
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main          
