name: Workflow Sekolahlinux

on:
  push:
    branches:
      - main

jobs:
  dev_packaging_stage:
    runs-on: sekolahlinux-runner
    container: ubuntu:20.04
    steps:
      - name: task1
        uses: actions/checkout@v3
      - name: task2
        run: |
          echo "hello world1"
          apt update && apt install curl -y
          curl icanhazip.com
